Feat/16
youngeek-0410/candle-backend pull request #17
Opened 2023-12-13 14:47 UTC by fuu38

close #16 
room_idを受けとり、未使用なら201(created)とroom_id,使用中なら409(conflict),を返す。
未使用のときはroomを作成する。ゲームが終わるのに充分な時間(とりあえず12h)経過したらプールに戻るよう、TTLもつけた。
![image](https://github.com/youngeek-0410/candle-backend/assets/49513840/73bf0ce3-1847-447a-9096-4d82139cd075)

2023-12-13 15:59 UTC, is-hoku requested changes
v1 か v2 どちらを使うかだけ認識合わせておきたいかなー

2023-12-13 15:59 UTC, is-hoku commented on lambda/room/POST/main.go
> +	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
v1 か v2 どちらかでなければいけない理由は無いけれど、コードの再利用とか参考にしやすさとか考えたら統一はした方がよさそう？まぁ決めの問題!

2023-12-13 15:59 UTC, is-hoku commented on lambda/room/POST/main.go
> +	exists := createRoom(cfg, ctx, req.RoomId, roomTableName)
返り値が bool のため内部でエラーを握り潰しているから、 createRoom で err を返すようにして handler 側でエラーハンドリングしてあげた方が親切そう (と思ったけど、エラーをログに流すとかしていないからこのままでもいいかも)

2023-12-13 16:46 UTC, fuu38 commented on lambda/room/POST/main.go
> +	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
ま統一するなら新しい方か？と思いつつ，ドキュメントとかの充実具合もよく分からん．
過去のまで修正する必要は無いけど，新規作るのはどっちにするかだけ決めとくか

2023-12-13 16:50 UTC, fuu38 commented on lambda/room/POST/main.go
> +	exists := createRoom(cfg, ctx, req.RoomId, roomTableName)
これは最終行を見てもらうと分かるんだけど，アイテムが存在するなら作成せずエラーを返す，て設定になってるのよね．だから作成エラー=既に存在する，と決め打って実装してる．
本当はまず取得試みる→存在判定→無ければ作成みたいなロジックを書いてエラーハンドリングは別でやるべきだけど，面倒だからこうなってる．
```go
func createRoom(cfg aws.Config, ctx context.Context, roomId, roomTableName string) bool {
	svc := dynamodb.NewFromConfig(cfg)
	ttl := time.Now().Add(12 * time.Hour).Unix()
	_, err := svc.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(roomTableName),
		Item: map[string]types.AttributeValue{
			"room_id":      &types.AttributeValueMemberS{Value: roomId},
			"participants": &types.AttributeValueMemberL{Value: []types.AttributeValue{}},
			"TTL":          &types.AttributeValueMemberN{Value: fmt.Sprintf("%v", ttl)},
		},
		ConditionExpression: aws.String("attribute_not_exists(room_id)"),
```

2023-12-14 03:04 UTC, is-hoku commented on lambda/room/POST/main.go
> +	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
https://aws.amazon.com/jp/blogs/developer/aws-sdk-for-go-version-2-general-availability/#:~:text=The%20AWS%20SDK%20for%20Go%20v2%20requires%20Go%201.15%20or,you%20already%20use%20version%201.
> The AWS SDK for Go v2 requires Go 1.15 or higher, and offers significant performance improvements in CPU and memory utilization over version 1. Review our Developer Guide to get started with AWS SDK for Go v2 or review the migration guide if you already use version 1.

こういう御触れがあったから、どっちでもいいなら v2 使っておけばいいかと思った

2023-12-14 04:01 UTC, GoRuGoo approved these changes

2023-12-14 04:27 UTC, is-hoku approved these changes
![](https://gist.githubusercontent.com/is-hoku/042948a30eb86f78ad9c21303cef3a76/raw/40319f6a185e31bd05c4505d3d1c3d227a1ce16d/IKnowGoVeryWell.png)

2023-12-14 04:41 UTC, fuu38 commented on lambda/room/POST/main.go
> +	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
OK!ではそれで

2023-12-14 04:42 UTC, merged