ルーム入室エンドポイント実装
youngeek-0410/candle-backend pull request #29
Opened 2023-12-17 18:44 UTC by GoRuGoo

close #18

2023-12-17 18:47 UTC, GoRuGoo commented
## QAエビデンス
Swaggerに指定された形式でリクエストを送る
![スクリーンショット 2023-12-18 3 45 14](https://github.com/youngeek-0410/candle-backend/assets/89027827/6d514271-2d42-479f-80a4-cd1feece0fe1)

正常なレスポンスが返ってくる
![スクリーンショット 2023-12-18 3 45 23](https://github.com/youngeek-0410/candle-backend/assets/89027827/d216014b-3e89-45ca-9aaa-a0025d72573c)

DBにも適切に値を書き込むことができている
```json
{
  "user_id": {
    "S": "01bc0364-86e4-43f6-9eb5-7ca03e2f990f"
  },
  "answers": {
    "L": [
      {
        "M": {
          "answer": {
            "BOOL": true
          },
          "question_id": {
            "S": "1"
          }
        }
      },
      {
        "M": {
          "answer": {
            "BOOL": true
          },
          "question_id": {
            "S": "2"
          }
        }
      },
      {
        "M": {
          "answer": {
            "BOOL": false
          },
          "question_id": {
            "S": "3"
          }
        }
      },
      {
        "M": {
          "answer": {
            "BOOL": false
          },
          "question_id": {
            "S": "4"
          }
        }
      },
      {
        "M": {
          "answer": {
            "BOOL": true
          },
          "question_id": {
            "S": "5"
          }
        }
      }
    ]
  },
  "nickname": {
    "S": "gorugo"
  },
  "room_name": {
    "S": "youngeek"
  }
}
```

2023-12-18 00:29 UTC, fuu38 requested changes

2023-12-18 00:29 UTC, fuu38 commented on lambda/room/{room_id}/POST/main.go
> +	if t, exists := os.LookupEnv("USER_ABLE_NAME"); exists {
typo

2023-12-18 00:29 UTC, fuu38 commented on lambda/room/{room_id}/POST/main.go
> +			"answers":   &types.AttributeValueMemberL{Value: answers},
全体で用語の統一したい。room_idかな

2023-12-18 01:09 UTC, is-hoku approved these changes
![](https://gist.githubusercontent.com/is-hoku/042948a30eb86f78ad9c21303cef3a76/raw/40319f6a185e31bd05c4505d3d1c3d227a1ce16d/IKnowGoVeryWell.png)

2023-12-18 03:31 UTC, fuu38 approved these changes

2023-12-18 04:07 UTC, merged